# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Build

on:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++, clang++]
        build-type: [Debug, Release]
        coverage: [false]
        include:
        - os: ubuntu-20.04
          cxx: g++
          build-type: Debug
          coverage: true
        - os: windows-latest
          cxx: clang++
          build-type: Debug
          coverage: false
        - os: macos-latest
          cxx: clang++
          build-type: Debug
          coverage: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jwlawson/actions-setup-cmake@v1

    - name: Build and tests
      run: |
        mkdir build
        cd build
        CXX=${{ matrix.cxx }} cmake -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ..
        cmake --build .
        ctest --output-on-failure

    - name: Coverage
      if: ${{ matrix.coverage }}
      run: |
        cd build
        bash <(curl -s https://codecov.io/bash)
